import os
import datetime


def save_document(response_text:str,directory: str = "./output"):
    """ Export travel plan to MarkDown file with proper formating"""

    os.makedirs(directory,exist_ok=True)


    #create markdown content with metadata header
    markdown_content = f"""# AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
    # ** Created by:** NG Travel Agencies

    ---

    {response_text}

    ---

    *This travel plan is generated by AI. Please verify all the information, especially price
    """
    try:

        #Write to markdown file with UTF-8 encoding
        #Generate timestamp-based filename

        timestamp = datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')
        filename = f"{directory}/AI_Travel_Plan_{timestamp}.md"
        
        print(filename)

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)

        print(f"Markdown file saved as: {filename}")
        return filename
    
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None
    